### ISSUE TITLE
Use bgrt plymouth theme

### ISSUE THREAD

**Issue by cassidyjames** [elementary/plymouth-theme#3]
Ubuntu added this in 20.04, mostly to appease folks like Dell and Lenovo. It's also a feature of Windows—and maybe it's an EFI-specific feature or something? Not 100% sure. 

It might be worth considering doing this as well since we've been working more closely with OEMs and they tend to like to get their branding into that power-on sequence—and modern machines have a _very_ short pre-OS boot time which makes flashing it before the elementary logo almost useless.

See also: Android devices where that's one of the few prominent OEM branding locations. :)

**Comment by AdrianVovk** [comment]
Hello! Sorry for the noise on this closed issue, but I had a question about plymouth's BGRT-fallback code and I don't think @meisenzahl is active on fd.o's gitlab. Please let me know if there is a better way to contact you

I'm currently trying to get the bgrt fallback working on my own distro, but I don't think that this is even possible with the code as-is. On systems that don't support BGRT (or `bgrt_disable` is passed on the kernel command line) I just get an empty black screen just as before, even though the `bgrt-fallback.png` is present and readable by Plymouth (when renaming it to `watermark.png`, Plymouth loads it right up)

I did some tracing through the code. I'll admit I'm not super familiar with Plymouth's internal makeup, but it seems to me like it is impossible for the image to render if the system does not have BGRT support. Here's why:
1) In `create_plugin`, `background_bgrt_fallback_image` is set, and then eventually `background_bgrt_image` is set
2) In `show_splash_screen`, Plymouth tries to load `background_bgrt_image`, and fails because `/sys/firmware/acpi/bgrt` doesn't exist. Therefore, it falls through to the fallback case and loads `background_bgrt_fallback_image` into `background_bgrt_image` instead. So far, so good: background_bgrt_image is correctly loaded with the fallback image
3) `show_splash_screen` calls `load_views`, which eventually calls `view_load`, which eventually calls `view_set_bgrt_background`, which is supposed to render the BGRT image
4) `view_set_bgrt_background` does a couple early checks. First, it checks if `background_bgrt_image` is set, which it is (to the fallback image). Next, it calls `get_bgrt_sysfs_info`, which queries various files in `/sys/firmware/acpi/bgrt` and **fails** if any of those files are missing or invalid. When `get_bgrt_sysfs_info` fails, `view_set_bgrt_background` logs an error and immediately returns without doing any rendering.
5) `view_load` continues drawing the rest of the screen without the fallback image

Were you able to get Plymouth to draw the fallback image in testing? Are there additional patches I'm missing?
